version: '3'
vars:
    NAME: "toggle"
    DOCKER_TAG: "toggle/server:dev"
    DOCKER_NAME: "toggle-api"
    GEN_DIR: "./internal/api"
    BIN_DIR: "./bin"
tasks:
    setup:
        desc: Install tools needed to develop Toggle
        cmds:
        - go install github.com/bufbuild/buf/cmd/buf@latest
        - go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest
        - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        - go install github.com/bufbuild/connect-go/cmd/protoc-gen-connect-go@latest
    generate:
        desc: Generate connect-go/gRPC integration code
        cmds:
        - buf generate
        sources: 
        - api/toggle/**/*.proto
        generates:
        - gen/go/**/*.go
    test:
        desc: Run the test suite
        cmds:
        - go test {{.CLI_ARGS}} ./...
    build:
        deps: [generate]
        desc: Build the Toggle API server and CLI client
        cmds:
        - go build -o {{.BIN_DIR}}/{{.NAME}} {{.CLI_ARGS}} main.go  # compile the code
    build-docker:
        desc: Generate the docker image
        cmds:
        - docker build --tag {{.DOCKER_TAG}} -f Dockerfile {{.CLI_ARGS}} .
    run:
        desc: Run Toggle from source
        cmds:
        - go run main.go {{.CLI_ARGS}}
    run-docker:
        desc: Run Toggle from the Docker image
        cmds:
        - docker run -it --rm -p 8080:8080 --name {{.DOCKER_NAME}} {{.CLI_ARGS}} {{.DOCKER_TAG}}